apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
      - name: provider
        image: minikube-project:v1
        ports:
        - containerPort: 3001
